rankIT-app/main/default/objects/RankIt_Settings__mdt/RankIt_Settings__mdt.object-meta.xml
<CustomObject>
    <label>RankIt Setting</label>
    <pluralLabel>RankIt Settings</pluralLabel>
</CustomObject>

rankIT-app/main/default/objects/RankIt_Settings__mdt/fields/ActiveInd__c.field-meta.xml
<CustomField>
    <fullName>ActiveInd__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Ind</label>
    <type>Checkbox</type>
</CustomField>

rankIT-app/main/default/objects/RankIt_Settings__mdt/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <inlineHelpText>The WHERE clause of the soql query</inlineHelpText>
    <label>Filter</label>
    <type>TextArea</type>
</CustomField>

rankIT-app/main/default/objects/RankIt_Settings__mdt/fields/Include_In_Tests__c.field-meta.xml
<CustomField>
    <fullName>Include_In_Tests__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if you want these rules included in deployment tests</inlineHelpText>
    <label>Include In Tests?</label>
    <type>Checkbox</type>
</CustomField>

rankIT-app/main/default/objects/RankIt_Settings__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>The object to which the setting applies</description>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

rankIT-app/main/default/objects/RankIt_Settings__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asc</fullName>
                <default>true</default>
                <label>Asc</label>
            </value>
            <value>
                <fullName>Desc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

rankIT-app/main/default/objects/RankIt_Settings__mdt/fields/Record_Limit__c.field-meta.xml
<CustomField>
    <fullName>Record_Limit__c</fullName>
    <label>Record Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

rankIT-app/main/default/objects/RankIt_Settings__mdt/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

rankIT-app/main/default/objects/RankIt_Settings__mdt/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <label>Target Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

rankIT-app/main/default/classes/RankITUtil.cls
public class RankITUtil {

    public static void sendFailureEmail(String subject, String emailBody) {
        
        List<String> toAddresses = new List<String>(); 
        for(ApexEmailNotification aen: [Select Id, User.Email, Email FROM ApexEmailNotification]) {
            if(aen.User.Email == null) {
                toAddresses.add(aen.Email);
            } else {
                toAddresses.add(aen.User.Email);
            }
        }

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSenderDisplayName('Salesforce - RankIt');
        mail.setSubject(subject);
        mail.setToAddresses(toAddresses);
        mail.setPlainTextBody(emailBody);

        if (toAddresses.size() > 0) {
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
        }
    }

    public static List<RankIt_Settings__mdt> getSettings(String objectName) {
        
        String settingsSoql = 'SELECT Id, Object__c, DeveloperName, Order__c, Source_Field__c,'
                        + 'Target_Field__c, Filter__c, Record_Limit__c '
                    + 'FROM RankIt_Settings__mdt '
                    + 'WHERE Object__c = \'' + objectName + '\'';

        if(!Test.isRunningTest()) {
            settingsSoql += ' AND ActiveInd__c = true';
        } else {
            settingsSoql += ' AND Include_In_Tests__c = true';
        }

        return database.query(settingsSoql + ' LIMIT 1');
    }
}